site:
    title: Ersel's Blog
    tagline: Tech, Business, Books and everything else...
posts:
    -
        title: "Artificial Intelligence: Key to the future or Pandora's box - part 1"
        filename: artificial-intelligence-essay-part1.html
        date: 2016-07-07
        template: post.html
        content: ai-essay-p1.md
        category: essays
